services:
  db:
    container_name: postgres_container
    image: postgres:14.17
    platform: linux/amd64 # Specifies the platform for Apple Silicon compatibility
    ports:
      - "5001:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  dbt:
    container_name: dbt_container
    image: ghcr.io/dbt-labs/dbt-postgres:1.8.1
    platform: linux/amd64
    
    # Mounts the current project directory (.) into '/app' inside the container
    volumes:
      - .:/app
      
    # Sets the default working directory inside the container
    working_dir: /app
    
    # ADD THIS LINE TO DISABLE THE DEFAULT ENTRYPOINT
    entrypoint: ""
    
    # This command now runs directly, keeping the container alive
    command: tail -f /dev/null
    
    # Ensures the dbt service only starts after the 'db' service is ready
    depends_on:
      - db