# Final and corrected docker-compose file for the entire data pipeline project.
# This version uses the 'user' directive for better permission handling with Airflow.

services:
  db:
    container_name: postgres_data_db
    image: postgres:14.17
    platform: linux/amd64
    ports:
      - "5001:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  dbt:
    container_name: dbt_container
    image: ghcr.io/dbt-labs/dbt-postgres:1.8.1
    platform: linux/amd64
    volumes:
      - .:/app
      - ./dbt/profiles:/root/.dbt
    working_dir: /app/dbt/weather_dw
    entrypoint: ""
    command: tail -f /dev/null
    environment:
      - DBT_USER=${POSTGRES_USER}
      - DBT_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db

  redis:
    container_name: redis_container
    image: redis:latest
    platform: linux/amd64
    ports:
      - "6379:6379"

  superset:
    container_name: superset_container
    image: apache/superset
    platform: linux/amd64
    ports:
      - "8088:8088"
    environment:
      # We only need the secret key here now
      - SUPERSET_SECRET_KEY=${SUPERSET_SECRET_KEY}
    volumes:
      - ./superset/data:/app/superset_home
      - ./superset/requirements-local.txt:/app/docker/requirements-local.txt
    depends_on:
      - db
      - redis

  postgres_airflow_db:
    image: postgres:13
    container_name: postgres_airflow_db
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      timeout: 5s
      retries: 5

  airflow-webserver:
    image: apache/airflow:2.8.1
    container_name: airflow_webserver
    command: webserver
    ports:
      - "8080:8080"
    user: "${AIRFLOW_UID:-50000}"
    depends_on:
      postgres_airflow_db:
        condition: service_healthy
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres_airflow_db:5432/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      # ADD THIS LINE to increase the webserver startup timeout to 300s
      - GUNICORN_CMD_ARGS=--timeout 300

  airflow-scheduler:
    image: apache/airflow:2.8.1
    container_name: airflow_scheduler
    command: scheduler
    user: "${AIRFLOW_UID:-50000}" # This is the corrected way to handle user permissions
    depends_on:
      postgres_airflow_db:
        condition: service_healthy
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres_airflow_db:5432/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor